### ISSUE TITLE
Unable to find release page for None

### ISSUE THREAD

**Issue by asim** [ConnectEverything/ngs-cli#10] opened 2018-12-21 12:07 UTC
I run into this issue when running the installer

```
$ curl https://downloads.synadia.com/ngs/install.py -sSf | python


Installing NGS tools for platform: darwin
Unable to find release page for None
```

**Comment by sasbury** [comment] 2018-12-21 19:44
Can you try again. I just ran it and didn't see an issue. Also can you run ` python --version` and let me know what you get.

**Comment by sasbury** [comment] 2018-12-21 19:45
worst case, you can download here - https://github.com/ConnectEverything/ngs-cli/releases/tag/v0.6.0 and unpack the binary, but i hope that isn't necessary.

**Comment by asim** [comment] 2018-12-21 19:48
Same issue. I'll use the binary. Thanks.

```
Python 2.7.10
```

**Comment by sasbury** [comment] 2018-12-21 19:50
very very weird, i just did it, we will investigate, thanks asim.

**Comment by asim** [comment] 2018-12-21 19:55
No worries. Not urgent. Feel free to backlog it for when you guys have time.

**Comment by sasbury** [comment] 2018-12-21 20:01
if you have time - can you try this:

 % curl https://downloads.synadia.com/ngs/install.py -sSf > tmp.py
 % python tmp.py v0.6.0 

basically download then run the script with a specific tag.

**Comment by asim** [comment] 2018-12-21 20:35
No luck. What base url are you providing? Because the link is [https://github.com/ConnectEverything/ngs-cli/releases/download/v0.6.0/ngs-darwin-amd64.zip](https://github.com/ConnectEverything/ngs-cli/releases/download/v0.6.0/ngs-darwin-amd64.zip) and your base uses "/releases/tag/"

```
$ curl https://downloads.synadia.com/ngs/install.py -sSf > tmp.py
$ python tmp.py v0.6.0

Installing NGS tools for platform: darwin
Unable to find release page for v0.6.0
```


```

**Comment by sasbury** [comment] 2018-12-21 20:46
the script is supposed to look at the web page, and extract the URL, so one is releases/tag and the other is the link on the page. But it is really weird, https://github.com/connecteverything/ngs-cli/releases/tag/v0.6.0 works for me, but somehow isn't working in the script for you.

**Comment by sasbury** [comment] 2019-11-17 06:13
I think this was a github throttling issue, now that I think some more. Closing for now. Please reopen if you are able to reproduce.

**Closed as completed by sasbury** 2019-11-17 06:13 UTC
